version: '3.9'

services:
  ex2-server:
    build:
      context: .
      dockerfile: Dockerfile.ex2
    container_name: ex2-server
    ports:
      - "5555:5555"
    command: ["./server", "5555"]

  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      EX2_HOST: "ex2-server"
      EX2_PORT: "5555"
      JWT_SECRET: "wolt_dev_secret_1234"
    depends_on:
      - ex2-server
